admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


analytics:
    pattern:  /analytics/{detail}
    defaults: { _controller: ZeegaAdminBundle:Analytics:index}