ZeegaEditorBundle_new:
    pattern: /project/new
    defaults: { _controller:  ZeegaEditorBundle:Editor:newProject }
    schemes:  [http]

ZeegaEditorBundle_editor:
    pattern: /editor/{id}
    defaults: { _controller:  ZeegaEditorBundle:Editor:editor }
