imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_prod.yml" }
    profiler: { only_exceptions: true }
    session:
        handler_id: snc_redis.session.handler

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

assetic:
    use_controller: true

snc_redis:
    session:
        client: session
        ttl: 1440000
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%event_logger_host%
        session:
            type: predis
            alias: session
            dsn: redis://%session_logger_host%
