<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120409132751 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
    //    $this->addSql("ALTER TABLE item ADD tags LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)'");
        
        
    }
    
    public function postUp(Schema $schema)
    {
        $conn = $this->connection;

        $sql = "SELECT id, layers FROM frame";
        $stmt = $conn->query($sql); // Simple, but has several drawbacks
        
        
        $insertSQL = "INSERT into frames_layers values(:frame_id, :layer_id)";
        
        while ($row = $stmt->fetch()) 
        {
            $frameId = $row["frame_id"];
            $layers = unserialize($row['layers']);
            
            foreach($layers as $layerId)
            {
                $conn->executeUpdate('INSERT into frames_layers (frame_id,layer_id) values(?, ?)', array($frameId, $layerId));
            }
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
      //  $this->addSql("ALTER TABLE item DROP tags");
    }
}
