<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120209145310 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        // 
        $this->addSql("ALTER TABLE Node RENAME Frame");
		$this->addSql("ALTER TABLE Route RENAME Sequence");
		$this->addSql("ALTER TABLE Playground RENAME Site");
		$this->addSql("ALTER TABLE users_playgrounds RENAME users_sites");
		$this->addSql("ALTER TABLE routes_layers RENAME sequences_layers");		
		
		// drop playground_id fk and index
        $this->addSql("ALTER TABLE Item DROP FOREIGN KEY FK_BF298A20F8FE9381");
        $this->addSql("DROP INDEX IDX_BF298A20F8FE9381 ON Item");
        $this->addSql("ALTER TABLE Item CHANGE playground_id site_id INT DEFAULT NULL");
		$this->addSql("CREATE INDEX IDX_BF298A20F6BD1646 ON Item (site_id)");
		$this->addSql("ALTER TABLE Item ADD CONSTRAINT FK_BF298A20F6BD1646 FOREIGN KEY (site_id) REFERENCES Site(id)");
        
		// project
		$this->addSql("ALTER TABLE Project DROP FOREIGN KEY FK_E00EE972F8FE9381");
		$this->addSql("DROP INDEX IDX_E00EE972F8FE9381 ON Project");
		$this->addSql("ALTER TABLE Project CHANGE playground_id site_id INT DEFAULT NULL");        
        $this->addSql("ALTER TABLE Project ADD CONSTRAINT FK_E00EE972F6BD1646 FOREIGN KEY (site_id) REFERENCES Site(id)");
		$this->addSql("CREATE INDEX IDX_E00EE972F6BD1646 ON Project (site_id)");
		
		// node -> frame
		$this->addSql("ALTER TABLE Frame DROP FOREIGN KEY FK_254D477B34ECB4E6");
		$this->addSql("ALTER TABLE Frame DROP FOREIGN KEY FK_254D477B993D08FC");
	    $this->addSql("ALTER TABLE Frame DROP FOREIGN KEY FK_254D477B6F5AF03F");
	    $this->addSql("ALTER TABLE Frame DROP FOREIGN KEY FK_254D477B9F0A94F7");
	    $this->addSql("ALTER TABLE Frame DROP FOREIGN KEY FK_254D477BAA9478C2");
		$this->addSql("DROP INDEX IDX_254D477B34ECB4E6 ON Frame");
		$this->addSql("DROP INDEX IDX_254D477BAA9478C2 ON Frame");
		$this->addSql("DROP INDEX IDX_254D477B6F5AF03F ON Frame");
		$this->addSql("DROP INDEX IDX_254D477B9F0A94F7 ON Frame");
		$this->addSql("DROP INDEX IDX_254D477B993D08FC ON Frame");
		$this->addSql("ALTER TABLE Frame CHANGE route_id sequence_id INT DEFAULT NULL");
		$this->addSql("ALTER TABLE Frame CHANGE route_index sequence_index INT DEFAULT NULL");
		$this->addSql("ALTER TABLE Frame ADD CONSTRAINT FK_743913C998FB19AE FOREIGN KEY (sequence_id) REFERENCES Sequence(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE Frame ADD CONSTRAINT FK_743913C9AA9478C2 FOREIGN KEY (link_up_id) REFERENCES Frame(id)");
        $this->addSql("ALTER TABLE Frame ADD CONSTRAINT FK_743913C96F5AF03F FOREIGN KEY (link_down_id) REFERENCES Frame(id)");
        $this->addSql("ALTER TABLE Frame ADD CONSTRAINT FK_743913C99F0A94F7 FOREIGN KEY (link_left_id) REFERENCES Frame(id)");
        $this->addSql("ALTER TABLE Frame ADD CONSTRAINT FK_743913C9993D08FC FOREIGN KEY (link_right_id) REFERENCES Frame(id)");
		
		// users_playgrounds -> users_sites
		$this->addSql("ALTER TABLE users_sites DROP FOREIGN KEY FK_946022D3F8FE9381");
		$this->addSql("DROP INDEX IDX_946022D3F8FE9381 ON users_sites");
		$this->addSql("ALTER TABLE users_sites CHANGE playground_id site_id INT NOT NULL");
        $this->addSql("ALTER TABLE users_sites ADD CONSTRAINT FK_5B770E2AF6BD1646 FOREIGN KEY (site_id) REFERENCES Site(id)");
		
		$this->addSql("ALTER TABLE sequences_layers DROP FOREIGN KEY FK_4931205234ECB4E6");
		$this->addSql("DROP INDEX IDX_4931205234ECB4E6 ON sequences_layers");
		$this->addSql("ALTER TABLE sequences_layers CHANGE route_id sequence_id INT NOT NULL");
        $this->addSql("ALTER TABLE sequences_layers ADD CONSTRAINT FK_8568B41298FB19AE FOREIGN KEY (sequence_id) REFERENCES Sequence(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
    }
}
