<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120321152049 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE item DROP FOREIGN KEY FK_BF298A20EA9FDD75");
        $this->addSql("ALTER TABLE item DROP FOREIGN KEY FK_BF298A20DC9EE959");
        $this->addSql("DROP TABLE TagCorrelation");
        $this->addSql("ALTER TABLE site CHANGE created_at date_created DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE itemtags ADD enabled TINYINT(1) DEFAULT NULL, CHANGE tag_date_created date_created DATETIME NOT NULL");
        $this->addSql("ALTER TABLE frame DROP FOREIGN KEY FK_743913C9993D08FC");
        $this->addSql("ALTER TABLE frame DROP FOREIGN KEY FK_743913C96F5AF03F");
        $this->addSql("ALTER TABLE frame DROP FOREIGN KEY FK_743913C99F0A94F7");
        $this->addSql("ALTER TABLE frame DROP FOREIGN KEY FK_743913C9AA9478C2");
        $this->addSql("DROP INDEX FK_743913C9AA9478C2 ON frame");
        $this->addSql("DROP INDEX FK_743913C96F5AF03F ON frame");
        $this->addSql("DROP INDEX FK_743913C99F0A94F7 ON frame");
        $this->addSql("DROP INDEX FK_743913C9993D08FC ON frame");
        $this->addSql("ALTER TABLE frame ADD enabled TINYINT(1) DEFAULT NULL, DROP link_right_id, DROP link_down_id, DROP link_left_id, DROP link_up_id, CHANGE thumb_url thumbnail_url VARCHAR(101) DEFAULT NULL");
        $this->addSql("ALTER TABLE layer DROP item_uri, DROP zindex");
        $this->addSql("ALTER TABLE project ADD date_created DATETIME NOT NULL, ADD enabled TINYINT(1) NOT NULL, DROP created_at, CHANGE published published TINYINT(1) NOT NULL");
        $this->addSql("DROP INDEX UNIQ_BF298A20EA9FDD75 ON item");
        $this->addSql("DROP INDEX UNIQ_BF298A20DC9EE959 ON item");
        $this->addSql("ALTER TABLE item ADD location VARCHAR(100) DEFAULT NULL, ADD license VARCHAR(50) DEFAULT NULL, ADD attributes LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', ADD enabled TINYINT(1) NOT NULL, ADD published TINYINT(1) NOT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE uri uri VARCHAR(255) NOT NULL, CHANGE attribution_uri attribution_uri VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE tag DROP description");
        $this->addSql("update item inner join metadata on item.metadata_id = metadata.id set item.license = metadata.license, item.attributes = metadata.attributes, item.archive = metadata.archive");
        $this->addSql("update item inner join metadata on item.metadata_id = metadata.id set item.thumbnail_url = metadata.thumbnail_url where item.thumbnail_url is null");
        $this->addSql("ALTER TABLE item DROP media_id, DROP metadata_id");
        $this->addSql("DROP TABLE media");
        $this->addSql("DROP TABLE metadata");
    }

    public function down(Schema $schema)
    {
    }
}
