<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120222175555 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE INDEX media_date_created_index ON item (media_date_created)");
        $this->addSql("CREATE INDEX media_date_created_end_index ON item (media_date_created_end)");
        $this->addSql("CREATE INDEX item_type_index ON item (layer_type)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX media_date_created_index ON Item");
        $this->addSql("DROP INDEX media_date_created_end_index ON Item");
        $this->addSql("DROP INDEX item_type_index ON Item");
    }
}
