<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120516180717 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE sequences_layers");
        $this->addSql("ALTER TABLE frame ADD project_id INT NOT NULL, DROP layers, CHANGE sequence_id sequence_id INT NOT NULL");
        $this->addSql("CREATE INDEX IDX_B5F83CCD166D1F9C ON frame (project_id)");
        $this->addSql("ALTER TABLE layer CHANGE project_id project_id INT NOT NULL");
        $this->addSql("ALTER TABLE sequence CHANGE project_id project_id INT NOT NULL");
        
        $this->addSql("UPDATE frame inner join sequence on frame.sequence_id = sequence.id set frame.project_id = sequence.project_id"); 
        $this->addSql("ALTER TABLE frame ADD CONSTRAINT FK_B5F83CCD166D1F9C FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE sequences_layers (sequence_id INT NOT NULL, layer_id BIGINT NOT NULL, INDEX IDX_49312052EA6EFDCD (layer_id), INDEX IDX_8568B41298FB19AE (sequence_id), PRIMARY KEY(sequence_id, layer_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE sequences_layers ADD CONSTRAINT FK_8568B41298FB19AE FOREIGN KEY (sequence_id) REFERENCES sequence(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE sequences_layers ADD CONSTRAINT FK_49312052EA6EFDCD FOREIGN KEY (layer_id) REFERENCES layer(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE frame DROP FOREIGN KEY FK_B5F83CCD166D1F9C");
        $this->addSql("DROP INDEX IDX_B5F83CCD166D1F9C ON frame");
        $this->addSql("ALTER TABLE frame ADD layers LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', DROP project_id, CHANGE sequence_id sequence_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE layer CHANGE project_id project_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE sequence CHANGE project_id project_id INT DEFAULT NULL");
    }
}
