ZeegaBookmarkletBundle_persist:
    pattern: /bookmarklet/persist
    defaults: { _controller:  ZeegaBookmarkletBundle:Bookmarklet:persist }

ZeegaBookmarkletBundle_widget:
    pattern: /bookmarklet/
    defaults: { _controller:  ZeegaBookmarkletBundle:Bookmarklet:open }
    requirements:
        _scheme:  https

ZeegaBookmarkletBundle_widget_secure:
    pattern: /secure/bookmarklet/
    defaults: { _controller:  ZeegaBookmarkletBundle:Bookmarklet:open }
    requirements:
        _scheme:  https
    
ZeegaBookmarkletBundle_persist_secure:
    pattern: /secure/bookmarklet/persist
    defaults: { _controller:  ZeegaBookmarkletBundle:Bookmarklet:persist }
    requirements:
        _scheme:  https
