ZeegaCommunityBundle_home:
    pattern:  /
    defaults: { _controller: ZeegaCommunityBundle:Community:home }

ZeegaCommunityBundle_tag:
    pattern:  /tag/{tag}
    defaults: { _controller: ZeegaCommunityBundle:Community:tag }

ZeegaCommunityBundle_user:
    pattern:  /profile/{id}
    defaults: { _controller: ZeegaCommunityBundle:Community:user }

ZeegaCommunityBundle_dashboard:
    pattern:  /dashboard
    defaults: { _controller: ZeegaCommunityBundle:Community:dashboard}

ZeegaCommunityBundle_team:
    pattern:  /team
    defaults: { _controller: ZeegaCommunityBundle:Community:team}

ZeegaCommunityBundle_contact:
    pattern:  /contact
    defaults: { _controller: ZeegaCommunityBundle:Community:contact}

ZeegaCommunityBundle_terms:
    pattern:  /terms
    defaults: { _controller: ZeegaCommunityBundle:Community:terms}

ZeegaCommunityBundle_privacy:
    pattern:  /privacy
    defaults: { _controller: ZeegaCommunityBundle:Community:privacy}

ZeegaCommunityBundle_faq:
    pattern: /faq
    defaults: { _controller: ZeegaCommunityBundle:Community:faq }

ZeegaCommunityBundle_notfound:
    pattern:  /notfound
    defaults: { _controller: ZeegaCommunityBundle:Community:notfound}

ZeegaCommunityBundle_makeday:
    pattern:  /events/tribecahacks
    defaults: { _controller: ZeegaCommunityBundle:Events:tribecahacks}
