ZeegaSocialBundle_twitter_connect:
    pattern:  /login/check-twitter

ZeegaSocialBundle_twitter_login_check:
    pattern:  /twitter/login_check
    defaults: { _controller: ZeegaSocialBundle:Twitter:securityCheck }

ZeegaSocialBundle_facebook_login_check:
    pattern:  /login/check-facebook
