<?php

namespace Zeega\IngestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemTagsRepository extends EntityRepository
{
}