<?php

namespace Zeega\IngestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagCorrelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagCorrelationRepository extends EntityRepository
{
    //  api/search
    public function searchRelatedTags($tagId)
    {
          $conn = $this->get('database_connection');

          $tags = $conn->fetchAll('select Tag.* from TagCorrelation 
                                   inner join Tag on TagCorrelation.tag_id = Tag.id where tag_id = ? order by correlation_index DESC',
                                   array(tagId));

          return $tags;
    }
}