<?php

namespace Zeega\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayerRepository extends EntityRepository
{
}