ZeegaPublishBundle_channel:
    pattern: /channel/{tag}
    defaults: { _controller:  ZeegaPublishBundle:Publish:channel }

ZeegaPublishBundle_frame_publish:
    pattern: /projects/{projectId}/frames/{frameId}
    defaults: { _controller:  ZeegaPublishBundle:Publish:frame }

ZeegaPublishBundle_collection_publish:
    pattern: /collection/{id}/view
    defaults: { _controller:  ZeegaPublishBundle:Publish:collection }

ZeegaPublishBundle_embed:
    pattern: /{id}/embed
    defaults: { _controller:  ZeegaPublishBundle:Publish:embed }

ZeegaPublishBundle_project_main:
    pattern: /{id}
    defaults: { _controller:  ZeegaPublishBundle:Publish:project, mobile: False }

ZeegaPublishBundle_project_mobile:
    pattern: /m/{id}
    defaults: { _controller:  ZeegaPublishBundle:Publish:project, mobile: True }

ZeegaPublishBundle_project_oldview:
    pattern: /{id}/view
    defaults: { _controller:  ZeegaPublishBundle:Publish:project }

ZeegaPublishBundle_project_altview:
    pattern: /project/{id}/view
    defaults: { _controller:  ZeegaPublishBundle:Publish:project }

ZeegaPublishBundle_project_preview:
    pattern: /projects/{id}/preview
    defaults: { _controller:  ZeegaPublishBundle:Publish:projectPreview }