ZeegaPublishBunde_channel:
    pattern: /channel/{tag}
    defaults: { _controller:  ZeegaPublishBunde:Publish:channel }

ZeegaPublishBunde_frame_publish:
    pattern: /frame/{id}/view
    defaults: { _controller:  ZeegaPublishBunde:Publish:frame }

ZeegaPublishBunde_collection_publish:
    pattern: /collection/{id}/view
    defaults: { _controller:  ZeegaPublishBunde:Publish:collection }

ZeegaPublishBunde_embed:
    pattern: /{id}/embed
    defaults: { _controller:  ZeegaPublishBunde:Publish:embed }

ZeegaPublishBunde_project_main:
    pattern: /{id}
    defaults: { _controller:  ZeegaPublishBunde:Publish:project, mobile: False }

ZeegaPublishBunde_project_mobile:
    pattern: /m/{id}
    defaults: { _controller:  ZeegaPublishBunde:Publish:project, mobile: True }

ZeegaPublishBunde_project_oldview:
    pattern: /{id}/view
    defaults: { _controller:  ZeegaPublishBunde:Publish:project }

ZeegaPublishBunde_project_altview:
    pattern: /project/{id}/view
    defaults: { _controller:  ZeegaPublishBunde:Publish:project }

ZeegaPublishBunde_project_preview:
    pattern: /projects/{id}/preview
    defaults: { _controller:  ZeegaPublishBunde:Publish:projectPreview }